DROP TABLE IF EXISTS member_referee CASCADE;
DROP TABLE IF EXISTS collectivity_member CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS activity CASCADE;
DROP TABLE IF EXISTS membership_fee CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS collectivity CASCADE;
DROP TABLE IF EXISTS financial_account CASCADE;

CREATE TABLE member ( 
     id VARCHAR(255) PRIMARY KEY, 
     first_name VARCHAR(255), 
     last_name VARCHAR(255), 
     birth_date DATE, 
     gender VARCHAR(50), 
     address VARCHAR(255), 
     profession VARCHAR(255), 
     phone_number VARCHAR(50), 
     email VARCHAR(255), 
     occupation VARCHAR(100), 
     membership_date DATE,
     registration_fee_paid BOOLEAN DEFAULT FALSE, 
     membership_dues_paid BOOLEAN DEFAULT FALSE 
 );

CREATE TABLE collectivity ( 
     id VARCHAR(255) PRIMARY KEY, 
     name VARCHAR(255), 
     number INTEGER, 
     location VARCHAR(255), 
     specialization VARCHAR(255), 
     president_id VARCHAR(255) REFERENCES member(id), 
     vice_president_id VARCHAR(255) REFERENCES member(id), 
     treasurer_id VARCHAR(255) REFERENCES member(id), 
     secretary_id VARCHAR(255) REFERENCES member(id) 
 );

CREATE TABLE collectivity_member ( 
     id VARCHAR(255) PRIMARY KEY, 
     member_id VARCHAR(255) REFERENCES member(id), 
     collectivity_id VARCHAR(255) REFERENCES collectivity(id) 
 );

CREATE TABLE member_referee ( 
     id VARCHAR(255) PRIMARY KEY, 
     member_refereed_id VARCHAR(255) REFERENCES member(id), 
     member_referee_id VARCHAR(255) REFERENCES member(id) 
 );

CREATE TABLE membership_fee (
    id VARCHAR(255) PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    label VARCHAR(255),
    frequency VARCHAR(50),
    eligible_from DATE,
    collectivity_id VARCHAR(255) REFERENCES collectivity(id)
);

CREATE TABLE financial_account (
    id VARCHAR(255) PRIMARY KEY,
    collectivity_id VARCHAR(255) REFERENCES collectivity(id),
    type VARCHAR(50),
    amount DOUBLE PRECISION DEFAULT 0,
    holder_name VARCHAR(255),
    phone_number VARCHAR(50),
    bank_name VARCHAR(255),
    bank_code VARCHAR(50),
    branch_code VARCHAR(50),
    account_number VARCHAR(255),
    rib_key VARCHAR(50)
);

CREATE TABLE payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    member_id VARCHAR(255) REFERENCES member(id),
    fee_id VARCHAR(255) REFERENCES membership_fee(id),
    account_id VARCHAR(255) REFERENCES financial_account(id),
    payment_mode VARCHAR(50)
);

CREATE TABLE activity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    mandatory BOOLEAN DEFAULT FALSE,
    target_audience VARCHAR(255),
    collectivity_id VARCHAR(255) REFERENCES collectivity(id)
);

CREATE TABLE attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id INTEGER REFERENCES activity(id),
    member_id VARCHAR(255) REFERENCES member(id),
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(255),
    locked BOOLEAN DEFAULT FALSE,
    UNIQUE(activity_id, member_id)
);
